image: registry.backpackcloud.com/backpackcloud/maven:1.0

stages:
  - build
  - release

mvn:package:
  stage: build
  artifacts:
    paths:
      - target/sherlog-holmes-runner
  script:
    - build

release:downstream:
  stage: release
  dependencies:
    - mvn:package
  script:
    - release