image: registry.backpackcloud.com/backpackcloud/maven

stages:
  - build
  - release

mvn:package:
  stage: build
  artifacts:
    paths:
      - target/sherlog-holmes-runner
  script:
    - build
    - upload target/sherlog-holmes-runner sherlog-holmes
