image: registry.backpackcloud.com/backpackcloud/maven

stages:
  - build
  - release

mvn:package:
  stage: build
  artifacts:
    paths:
      - target/sherlog-holmes
  script:
    - build
    - mv target/sherlog-holmes-runner sherlog-holmes
