image: golang:latest

variables:
  REPO_NAME: github.com/devnull-tools/sherlog-holmes

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - release

go:test:
  stage: test
  script:
    - go get ./...
    - go vet ./...
    - go test -race ./...

go:build:macos:amd64:
  stage: build
  only:
    - tags
  script:
    - go get ./...
    - GOOS=darwin GOARCH=amd64 go build -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/bin/sherlog-holmes
    - cd $CI_PROJECT_DIR/bin && tar -cvzf sherlog-holmes.$CI_COMMIT_TAG.darwin-amd64.tar.gz sherlog-holmes
  artifacts:
    expire_in: 2 days
    paths:
      - bin/macos/amd64/sherlog-holmes

go:build:linux:amd64:
  stage: build
  only:
    - tags
  script:
    - go get ./...
    - GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/bin/sherlog-holmes
    - cd $CI_PROJECT_DIR/bin && tar -cvzf sherlog-holmes.$CI_COMMIT_TAG.linux-amd64.tar.gz sherlog-holmes
  artifacts:
    expire_in: 2 days
    paths:
      - bin/linux/amd64/sherlog-holmes

go:build:windows:amd64:
  stage: build
  only:
    - tags
  script:
    - go get ./...
    - GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/bin/sherlog-holmes
    - cd $CI_PROJECT_DIR/bin && tar -cvzf sherlog-holmes.$CI_COMMIT_TAG.windows-amd64.tar.gz sherlog-holmes
  artifacts:
    expire_in: 2 days
    paths:
      - bin/windows/amd64/sherlog-holmes

nexus:release:
  stage: release
  only:
    - tags
  dependencies:
    - go:build:macos:amd64
    - go:build:linux:amd64
    - go:build:windows:amd64
  script:
    - curl -v -u $NEXUS_AUTH --upload-file $CI_PROJECT_DIR/bin/sherlog-holmes.$CI_COMMIT_TAG.darwin-amd64.tar.gz $NEXUS_URL/$NEXUS_REPO/$CI_COMMIT_TAG/sherlog-holmes.$CI_COMMIT_TAG.darwin-amd64.tar.gz
    - curl -v -u $NEXUS_AUTH --upload-file $CI_PROJECT_DIR/bin/sherlog-holmes.$CI_COMMIT_TAG.linux-amd64.tar.gz $NEXUS_URL/$NEXUS_REPO/$CI_COMMIT_TAG/sherlog-holmes.$CI_COMMIT_TAG.linux-amd64.tar.gz
    - curl -v -u $NEXUS_AUTH --upload-file $CI_PROJECT_DIR/bin/sherlog-holmes.$CI_COMMIT_TAG.windows-amd64.tar.gz $NEXUS_URL/$NEXUS_REPO/$CI_COMMIT_TAG/sherlog-holmes.$CI_COMMIT_TAG.windows-amd64.tar.gz
