models:
  nexus-log:
    format: '{@exception}{#timestamp} {#level|-5} {#thread} {#initiator} [{#domain},{#type},{#context}] {#class} {#message}'
    attributes:
      timestamp:
        type:      zoned-datetime
        indexable: false
        format:    yyyy-MM-dd HH:mm:ss,SSSZ

      level:
        type:      enum
        indexable: true
        values:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL

      thread:
        type:      text
        indexable: true

      initiator:
        type:      text
        indexable: true

      class:
        type:      text
        indexable: true

      exception:
        type:        text
        indexable:   true
        multivalued: true

      message:
        type:      text
        identity:  true
        indexable: false

  nexus-audit:
    format: |
      {#timestamp} {#initiator} {#thread} {#message}
      domain: {domain}
      type: {type}
      context: {context}
    attributes:
      timestamp:
        type:      zoned-datetime
        indexable: false
        format:    yyyy-MM-dd HH:mm:ss,SSSZ

      thread:
        type:      text
        indexable: true

      domain:
        type:      text
        indexable: true

      type:
        type:      text
        indexable: true

      context:
        type:      text
        indexable: true

      initiator:
        type:      text
        indexable: true

      message:
        type:      text
        identity:  true
        indexable: false

readers:
  plain-log:
    type:               line
    charset:            UTF-8
    new-entry:          '{{timestamp}}'
    remove-ansi-colors: true
  json-log:
    type:    json
    charset: UTF-8

parsers:
  nexus-log:
    type:    regex
    pattern: '{{timestamp}} {{level}}\s+{{thread}}  {{initiator}} {{class}} - {{message}}'

  nexus-audit:
    type:  map
    attributes:
      timestamp: /timestamp
      initiator: /initiator
      domain:    /domain
      type:      /attributes/.typeId
      context:   /context
      thread:    /thread
      message:   /attributes/.message

patterns:
  timestamp: '(?<timestamp>\d{2,4}-\d{2}-\d{2,4} \d{2}:\d{2}:\d{2},\d{3}[+-]\d{4})'
  level:     '(?<level>\w+)'
  thread:    '\[(?<thread>[^]]+)]'
  initiator: '(?<initiator>\*\S+)'
  class:     '(?<class>\S+)'
  message:   '(?<message>.+)'

pipeline:
  - map:
      from:  message
      regex: '(?<exception>\w+(\.\w+)+(Exception|Error))'

icons:
  attribute-timestamp: nf-fa-calendar
  attribute-level:     nf-fa-signal
  attribute-thread:    nf-fa-code_fork
  attribute-initiator: nf-fa-folder_open
  attribute-class:     nf-dev-java
  attribute-message:   nf-mdi-message
  attribute-exception: nf-fa-bug

styles:
  attribute-timestamp:   grey//i

  attribute-level-TRACE: cyan
  attribute-level-DEBUG: cyan
  attribute-level-INFO:  orange
  attribute-level-WARN:  yellow
  attribute-level-ERROR: red//b
  attribute-level-FATAL: red//b

  attribute-thread:      blue
  attribute-initiator:   grey
  attribute-message:     white
  attribute-exception:   red
  attribute-class:       yellow
