filter_grouping:   white
filter_operation:  purple

filter:            white

name:              white
count:             blue
percentage:        orange
separator:         white
total:             white

icon-data:         blue
icon-time-range:   purple
icon-stack:        orange

attribute-$source: purple
attribute-$line:   purple
