data:                ""
filter:              ""
limit:               "󰃕"
stack:               ""
time-range:          "󰔚"

attribute-source:    ""
attribute-timestamp: ""
attribute-message:   "󰍧"
