preferences:
  default-fallback-mode: append
  show-added-entries:    true
  add-metadata:          true
  remove-ansi-colors:    true

models:
  java:
    format: '{@exception}{#timestamp} {#level|-5} {#category} {#thread} {#message}'
    attributes:
      timestamp: datetime | yyyy-MM-dd HH:mm:ss,SSS
      level:     enum | TRACE,DEBUG,INFO,WARN,ERROR,FATAL
      category:  text
      thread:    text
      exception: text[]
      message:   text
      code:      text

index:
  - level
  - category
  - thread
  - exception
  - code

readers:
  file:
    type:    file
    charset: UTF-8

  socket:
    type:    socket
    charset: UTF-8

parsers:
  infinispan:
    type:    regex
    pattern: '{{timestamp}} {{level}}\s+{{thread}} {{category}} {{message}}'

  wildfly:
    type:    regex
    pattern: '{{timestamp}} {{level}}\s+{{category}} {{thread}} {{message}}'

mappers:
  java:
    type: function
    copy: timestamp,level,category,thread,code,message

patterns:
  timestamp: '(?<timestamp>\d{2,4}-\d{2}-\d{2,4} \d{2}:\d{2}:\d{2},\d{3})'
  level:     '(?<level>\w+)'
  category:  '\[(?<category>[^]]+)]'
  thread:    '\((?<thread>[^)]+)\)'
  message:   '(?<message>((?<code>\w{4,}): )?.+)'

steps:
  java:
    - map:
        from:  message
        regex: '(?<exception>\w+(\.\w+)+(Exception|Error))'

pipelines:
  wildfly:
    model:  java
    parser: wildfly
    mapper: java
    steps:  java

  infinispan:
    model:  java
    parser: infinispan
    mapper: java
    steps:  java

exporters:
  json:
    type:       json
    attributes: timestamp,level,category,thread,code,message

icons:
  attribute-timestamp: nf-fa-calendar
  attribute-level:     nf-fa-signal
  attribute-category:  nf-fa-folder_open
  attribute-thread:    nf-fa-code_fork
  attribute-message:   nf-mdi-message
  attribute-exception: nf-fa-bug

styles:
  attribute-timestamp:   grey//i

  attribute-level-TRACE: cyan
  attribute-level-DEBUG: cyan
  attribute-level-INFO:  orange
  attribute-level-WARN:  yellow
  attribute-level-ERROR: red//b
  attribute-level-FATAL: red//b

  attribute-category:    blue
  attribute-thread:      grey
  attribute-message:     white
  attribute-exception:   red
